var libros = [
    {
        id: 1,
        nombre: "La Bruja ring ring 1",
        img: "./img/libro1.jpg",
        // titulo: "La guardiana del bosque",
        titulo: "LA GUARDIANA DEL BOSQUE",
        subtitulo: "La magia más poderosa de una bruja está en su corazón.",
        descripcion: "libro1",
        // descripcion:   "Lily es una aprendiz de bruja y guardiana del bosque. Vive con su abuela Hierbabuena en una encantadora cabaña en el bosque. Puede hablar con los animales y está aprendiendo a hacer magia con pócimas y hechizos que lanza con su varita."+
        //                 "Lily es dulce, cariñosa y valiente. Le gusta mucho dibujar y lleva a todas partes un cuaderno donde apunta recetas mágicas y dibuja animales. A Lily le encanta volar con su escoba, que tiene incorporado un manillar de bici con un timbre. Los animales la llaman la bruja Ring Ring por el ruido que hace el timbre: cuando oyen ese sonido saben que ¡Lily llega al rescate!",
        editorial: "LA GALERA",
        cajaLibro: "cajaLibro",
        ancho: null,
        alto: null,
        resumen: "Lily es una aprendiz de bruja y guardiana del bosque. Vive con su abuela Hierbabuena en una encantadora cabaña en el bosque. Puede hablar con los animales y está aprendiendo a hacer magia con pócimas y hechizos que lanza con su varita. " +
            "Lily es dulce, cariñosa y valiente. Le gusta mucho dibujar y lleva a todas partes un cuaderno donde apunta recetas mágicas y dibuja animales. A Lily le encanta volar con su escoba, que tiene incorporado un manillar de bici con un timbre. Los animales la llaman la bruja Ring Ring por el ruido que hace el timbre: cuando oyen ese sonido saben que ¡Lily llega al rescate!",


    },
    {
        id: 2,
        nombre: "La Bruja ring ring 2",
        img: "./img/libro2.jpg",
        // titulo: "El hechizo de la lluvia",
        titulo: "EL HECHIZO DE LA LLUVIA",
        subtitulo: "Una aprendiz de bruja con una misión: convertirse en la mejor guardiana del bosque.",
        descripcion: "libro2",
        // descripcion:"No hay nada más desesperante para una bruja que intentar hacer un hechizo y que no le salga como debería. El hechizo de lluvia es uno de los más difíciles, y a Lily le sale fatal. Ha conseguido que lluevan castañas, confeti y, en una ocasión, incluso galletitas. Pero Lily tiene que aprender a hacer este hechizo. Porque el agua es vida y sin agua no hay bosque.",
        editorial: "LA GALERA",
        cajaLibro: "cajaLibro",
        ancho: null,
        alto: null,
        resumen: "No hay nada más desesperante para una bruja que intentar hacer un hechizo y que no le salga como debería. El hechizo de lluvia es uno de los más difíciles, y a Lily le sale fatal. Ha conseguido que lluevan castañas, confeti y, en una ocasión, incluso galletitas. Pero Lily tiene que aprender a hacer este hechizo. Porque el agua es vida y sin agua no hay bosque."
    },
    {
        id: 3,
        nombre: "La Bruja ring ring 3",
        img: "./img/libro3.jpg",
        // titulo: "El gran rescate",
        titulo: "EL GRAN RESCATE",
        subtitulo: "La magia más poderosa de una bruja está en su corazón.",
        descripcion: "libro3",
        // descripcion:"Un circo acaba de instalar su carpa cerca del bosque donde Lily vive con su abuela. La curiosidad de la brujita es tan grande que decide acercarse para conocer de cerca a los humanos. Ilusionada por descubrir los trucos del gran Mago Marconio, Lily asistirá a su espectáculo de magia...pero descubrirá un truco que no le gustará ni pizca."+
        // "¡La bruja Ring Ring acude de nuevo al rescate de un animalito indefenso!",
        editorial: "LA GALERA",
        cajaLibro: "cajaLibroUltima",
        ancho: null,
        alto: null,
        resumen: "Un circo acaba de instalar su carpa cerca del bosque donde Lily vive con su abuela. La curiosidad de la brujita es tan grande que decide acercarse para conocer de cerca a los humanos. Ilusionada por descubrir los trucos del gran Mago Marconio, Lily asistirá a su espectáculo de magia...pero descubrirá un truco que no le gustará ni pizca." +
            "¡La bruja Ring Ring acude de nuevo al rescate de un animalito indefenso!"
    },
    // {
    //     id: 4,
    //     nombre: "La Bruja ring ring 4",
    //     img: "./img/FgfOmYRXwAEFmRn.jpeg",
    //     subtitulo: "",
    //     descripcion: "libro4",
    //     ancho: null,
    //     alto: null,
    //     cajaLibro: "cajaLibro",
    //     editorial: "",
    // },
    // {
    //     id: 5,
    //     nombre: "La Bruja ring ring 5",
    //     img: "./img/FgfOmYRXwAEFmRn.jpeg",
    //     subtitulo: "",
    //     descripcion: "libro5",
    //     cajaLibro: "cajaLibroUltima",
    //     editorial: "",
    //     ancho: null,
    //     alto: null,
    // },
];
var portfolio = [
    { id: 2, nombre: "La Bruja ring ring 2", img: "./img/portfolio/img1.png", ancho:"200", alto:"300",},
    { id: 3, nombre: "La Bruja ring ring 3", img: "./img/portfolio/img2.png", ancho:"350", alto:"400", },
    { id: 5, nombre: "La Bruja ring ring 5", img: "./img/portfolio/img3.png", ancho:"350", alto:"400", },
    { id: 5, nombre: "La Bruja ring ring 5", img: "./img/portfolio/img4.png", ancho:"350", alto:"400", },
    { id: 5, nombre: "La Bruja ring ring 5", img: "./img/portfolio/img5.png", ancho:"350", alto:"400", },
    { id: 5, nombre: "La Bruja ring ring 5", img: "./img/portfolio/img6.png", ancho:"350", alto:"400", },
    { id: 5, nombre: "La Bruja ring ring 5", img: "./img/portfolio/img7.png", ancho:"350", alto:"400", },
    { id: 1, nombre: "La Bruja ring ring 1", img: "./img/libro1.jpg", ancho:"452", alto:"546", },
    { id: 2, nombre: "La Bruja ring ring 2", img: "./img/libro2.jpg", ancho:"252", alto:"346", },
    { id: 3, nombre: "La Bruja ring ring 3", img: "./img/libro3.jpg", ancho:"350", alto:"400", },
    { id: 5, nombre: "La Bruja ring ring 5", img: "./img/FgfOmYRXwAEFmRn.jpeg", ancho:"350", alto:"400", },
    { id: 2, nombre: "La Bruja ring ring 2", img: "./img/portfolio/img1.png", ancho:"200", alto:"300",},
    { id: 3, nombre: "La Bruja ring ring 3", img: "./img/portfolio/img2.png", ancho:"350", alto:"400", },
    { id: 5, nombre: "La Bruja ring ring 5", img: "./img/portfolio/img3.png", ancho:"350", alto:"400", },
    { id: 5, nombre: "La Bruja ring ring 5", img: "./img/portfolio/img4.png", ancho:"350", alto:"400", },
    { id: 5, nombre: "La Bruja ring ring 5", img: "./img/portfolio/img5.png", ancho:"350", alto:"400", },
    { id: 5, nombre: "La Bruja ring ring 5", img: "./img/portfolio/img6.png", ancho:"350", alto:"400", },
    { id: 5, nombre: "La Bruja ring ring 5", img: "./img/portfolio/img7.png", ancho:"350", alto:"400", },
    { id: 1, nombre: "La Bruja ring ring 1", img: "./img/libro1.jpg", ancho:"452", alto:"546", },
    { id: 2, nombre: "La Bruja ring ring 2", img: "./img/libro2.jpg", ancho:"252", alto:"346", },    
    { id: 3, nombre: "La Bruja ring ring 3", img: "./img/libro3.jpg", ancho:"350", alto:"400", },
    { id: 5, nombre: "La Bruja ring ring 5", img: "./img/FgfOmYRXwAEFmRn.jpeg", ancho:"350", alto:"400", },
    { id: 2, nombre: "La Bruja ring ring 2", img: "./img/portfolio/img1.png", ancho:"200", alto:"300",},
    { id: 3, nombre: "La Bruja ring ring 3", img: "./img/portfolio/img2.png", ancho:"350", alto:"400", },
    { id: 5, nombre: "La Bruja ring ring 5", img: "./img/portfolio/img3.png", ancho:"350", alto:"400", },
    { id: 5, nombre: "La Bruja ring ring 5", img: "./img/portfolio/img4.png", ancho:"350", alto:"400", },
    { id: 5, nombre: "La Bruja ring ring 5", img: "./img/portfolio/img5.png", ancho:"350", alto:"400", },
    { id: 5, nombre: "La Bruja ring ring 5", img: "./img/portfolio/img6.png", ancho:"350", alto:"400", },
    { id: 5, nombre: "La Bruja ring ring 5", img: "./img/portfolio/img7.png", ancho:"350", alto:"400", },
    { id: 1, nombre: "La Bruja ring ring 1", img: "./img/libro1.jpg", ancho:"452", alto:"546", },
    { id: 2, nombre: "La Bruja ring ring 2", img: "./img/libro2.jpg", ancho:"252", alto:"346", },    
    { id: 3, nombre: "La Bruja ring ring 3", img: "./img/libro3.jpg", ancho:"350", alto:"400", },
    { id: 5, nombre: "La Bruja ring ring 5", img: "./img/FgfOmYRXwAEFmRn.jpeg", ancho:"350", alto:"400", },
    { id: 2, nombre: "La Bruja ring ring 2", img: "./img/portfolio/img1.png", ancho:"200", alto:"300",},
    { id: 3, nombre: "La Bruja ring ring 3", img: "./img/portfolio/img2.png", ancho:"350", alto:"400", },
    { id: 5, nombre: "La Bruja ring ring 5", img: "./img/portfolio/img3.png", ancho:"350", alto:"400", },
    { id: 5, nombre: "La Bruja ring ring 5", img: "./img/portfolio/img4.png", ancho:"350", alto:"400", },
    { id: 5, nombre: "La Bruja ring ring 5", img: "./img/portfolio/img5.png", ancho:"350", alto:"400", },
    { id: 5, nombre: "La Bruja ring ring 5", img: "./img/portfolio/img6.png", ancho:"350", alto:"400", },
    { id: 5, nombre: "La Bruja ring ring 5", img: "./img/portfolio/img7.png", ancho:"350", alto:"400", },
    { id: 1, nombre: "La Bruja ring ring 1", img: "./img/libro1.jpg", ancho:"452", alto:"546", },
    { id: 2, nombre: "La Bruja ring ring 2", img: "./img/libro2.jpg", ancho:"252", alto:"346", },   
    { id: 3, nombre: "La Bruja ring ring 3", img: "./img/libro3.jpg", ancho:"350", alto:"400", },
    { id: 5, nombre: "La Bruja ring ring 5", img: "./img/FgfOmYRXwAEFmRn.jpeg", ancho:"350", alto:"400", },
    { id: 2, nombre: "La Bruja ring ring 2", img: "./img/portfolio/img1.png", ancho:"200", alto:"300",},
    { id: 3, nombre: "La Bruja ring ring 3", img: "./img/portfolio/img2.png", ancho:"350", alto:"400", },
    { id: 5, nombre: "La Bruja ring ring 5", img: "./img/portfolio/img3.png", ancho:"350", alto:"400", },
    { id: 5, nombre: "La Bruja ring ring 5", img: "./img/portfolio/img4.png", ancho:"350", alto:"400", },
    { id: 5, nombre: "La Bruja ring ring 5", img: "./img/portfolio/img5.png", ancho:"350", alto:"400", },
    { id: 5, nombre: "La Bruja ring ring 5", img: "./img/portfolio/img6.png", ancho:"350", alto:"400", },
    { id: 5, nombre: "La Bruja ring ring 5", img: "./img/portfolio/img7.png", ancho:"350", alto:"400", },
    { id: 1, nombre: "La Bruja ring ring 1", img: "./img/libro1.jpg", ancho:"452", alto:"546", },
    { id: 2, nombre: "La Bruja ring ring 2", img: "./img/libro2.jpg", ancho:"252", alto:"346", },    
    { id: 3, nombre: "La Bruja ring ring 3", img: "./img/libro3.jpg", ancho:"350", alto:"400", },
    { id: 5, nombre: "La Bruja ring ring 5", img: "./img/FgfOmYRXwAEFmRn.jpeg", ancho:"350", alto:"400", },




   
];

var links = [
    {chm_id:1, nombre:"facebook", imgUrl:"./img/facebook.png", url:"www.facebook.com/aliciateba"},
    {chm_id:1, nombre:"instagram", imgUrl:"./img/instagram.png", url:"www.instagram.com/aliciateba"},
    {chm_id:1, nombre:"twitter", imgUrl:"./img/twitter.png", url:"www.twitter.com/aliciateba"},
    {chm_id:1, nombre:"lacasadellibro", imgUrl:"./img/laCasaDelLibro.png", url:"www.laCasaDelLibro.com/aliciateba"},
    {chm_id:1, nombre:"amazon", imgUrl:"./img/amazon.png", url:"www.amazon.com/aliciateba"},
    {chm_id:1, nombre:"fnac", imgUrl:"./img/fnac.png", url:"www.fnac.com/aliciateba"},
    {chm_id:1, nombre:"linkedin", imgUrl:"./img/linkedin.png", url:"www.linkedin.com/aliciateba"},
];